name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  packages: write

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          cd juice-shop && npm install --no-audit --no-fund --legacy-peer-deps
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Juice-Shop'
          path: "./juice-shop/"
          format: "SARIF"
          args: "--fail_on_severity NONE"  # Wyłącz failowanie na podatnościach
      - name: Upload Dependency-Check results
        uses: github/codeql-action/upload-sarif@v3
        if: always()  # Zawsze przesyła wyniki, nawet przy błędach
        with:
          sarif_file: ./dependency-check-report.sarif

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gtileaks.toml
          report-format: sarif
          report-path: gitleaks-results.sarif
        continue-on-error: true
      - name: Upload Gitleaks results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ./gitleaks-results.sarif

  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          semgrep scan --config=p/owasp-juice-shop --sarif --output=semgrep-results.sarif
          exit 0  # Wyłącz failowanie
      - name: Upload Semgrep results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ./semgrep-results.sarif

  build-and-scan:
    needs: [dependency-check, gitleaks, semgrep]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: yourusername/juice-shop
          tags: |
            type=raw,value=latest
            type=sha
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./juice-shop
          file: ./juice-shop/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: yourusername/juice-shop:latest
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          exit-code: 0
      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ./trivy-results.sarif

  dast-scan:
    needs: build-and-scan
    if: always()  # Wykonuj nawet jeśli build-and-scan failuje
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Juice Shop container
        run: |
          docker run -d --name juice-shop -p 3000:3000 local-scan:latest
          sleep 10
      - name: Run OWASP ZAP scan
        uses: zaproxy/action-baseline@v0.1.0
        with:
          target: "http://localhost:3000"
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_image: "ghcr.io/zaproxy/zaproxy:stable"
          cmd_options: "--exit-code Never"  # Wyłącz failowanie
      - name: Stop Juice Shop container
        if: always()
        run: docker stop juice-shop
